#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { DISCOVERY_LIMITS, collectMarkdown, firstHeading, isInsideRoot, parseArgs, readDescriptorBounded, readRegularFileBounded, resolveProjectRoot, safePath } from "./lib/core.mjs";

const args = parseArgs(process.argv.slice(2));
const outputPath = safePath(args.root, "ai-context/maps/CONTEXT_INDEX.md");
const documents = collectMarkdown(args.root)
  .filter((doc) => doc.relativePath !== "ai-context/maps/CONTEXT_INDEX.md")
  .map((doc) => ({
    id: doc.data.id || "—",
    type: doc.data.type || "unclassified",
    status: doc.data.status || "—",
    authority: doc.data.authority || "—",
    visibility: doc.data.visibility || "—",
    updated: doc.data.updated || "—",
    title: firstHeading(doc.body, path.basename(doc.relativePath)),
    path: doc.relativePath,
  }))
  .sort((left, right) => left.path.localeCompare(right.path));
const rows = documents.map((doc) => `| ${doc.id} | ${doc.type} | ${doc.status} | ${doc.authority} | ${doc.visibility} | ${doc.updated} | \`${doc.path}\` |`);
const generated = `---
context_version: 2
id: AICK-MAP-CONTEXT-INDEX
type: index
status: active
authority: derived
visibility: internal
updated: ${new Date().toISOString().slice(0, 10)}
---

<!-- generated by tools/context/index.mjs; do not edit manually -->

# Context Index

Generated inventory. Canonical facts remain in the owners named by \`ai-context/maps/SOURCE_OF_TRUTH_MAP.md\`.

| ID | Type | Status | Authority | Visibility | Updated | Path |
| --- | --- | --- | --- | --- | --- | --- |
${rows.join("\n")}
`;
if (args.check) {
  const current = fs.existsSync(outputPath) ? readRegularFileBounded(args.root, outputPath, DISCOVERY_LIMITS.maxFileBytes) : "";
  if (current !== generated) {
    console.error("CONTEXT_INDEX.md is out of sync. Run: node tools/context/index.mjs");
    process.exitCode = 1;
  }
} else {
  const realRoot = resolveProjectRoot(args.root);
  const outputDirectory = safePath(realRoot, "ai-context/maps");
  if (!fs.existsSync(outputDirectory)) throw new Error("Output directory must already exist; initialize the context structure first");
  const realOutputDirectory = fs.realpathSync.native(outputDirectory);
  if (!isInsideRoot(realRoot, realOutputDirectory)) throw new Error("Output directory resolves outside project root");
  if (fs.existsSync(outputPath)) {
    const descriptor = fs.openSync(outputPath, "r+");
    try {
      const openedStat = fs.fstatSync(descriptor);
      const realOutput = fs.realpathSync.native(outputPath);
      if (!isInsideRoot(realRoot, realOutput)) throw new Error("Generated index resolves outside project root");
      const currentStat = fs.statSync(realOutput);
      if (openedStat.dev !== currentStat.dev || openedStat.ino !== currentStat.ino) throw new Error("Generated index changed during validation");
      const current = readDescriptorBounded(descriptor, DISCOVERY_LIMITS.maxFileBytes);
      if (!current.includes("<!-- generated by tools/context/index.mjs; do not edit manually -->")) throw new Error("Refusing to overwrite an unmarked context index");
      fs.ftruncateSync(descriptor, 0);
      fs.writeSync(descriptor, generated, 0, "utf8");
      fs.fsyncSync(descriptor);
    } finally {
      fs.closeSync(descriptor);
    }
  } else {
    throw new Error("Generated context index does not exist; create it from the template through the normal project file-editing workflow before synchronization");
  }
  console.log(`Generated ${path.relative(args.root, outputPath)}`);
}
